title: rpi-gpio-pins
hero_image: images/banner.png
subtitle: rpi-gpio-pins subtitle
description: rpi-gpio-pins description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
