title: The Raspberry Pi's GPIO pins
hero_image: images/banner.png
description: GPIO pins on the Raspberry Pi
original_url:
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: GPIO pins

