---
title: Raspberry Pi的GPIO引脚
hero_image: images/banner.png
description: Raspberry Pi上的GPIO引脚
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: GPIO引脚

