---
title: Die GPIO-Stifte des Raspberry Pi
hero_image: images/banner.png
description: GPIO-Stifte am Raspberry Pi
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: GPIO-Stifte

