---
title: 라즈베리 파이의 GPIO 핀
hero_image: images/banner.png
description: 라즈베리 파이의 GPIO 핀
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: GPIO 핀

